# Tmux settings
set -s escape-time 0

# Set XTerm key bindings
# set-option -g xterm-keys on

set -g mouse on
set -g default-terminal "tmux-256color"

# Set reload key to r
bind r source-file ~/.tmux.conf

set -g prefix C-a
unbind C-b
bind C-a send-prefix

# go to last window
bind-key u last-window

# Count sessions start at 1
set -g base-index 1

# Use vim bindings
setw -g mode-keys vi
bind C-l send-keys 'C-l'

#
# Set the title bar
set -g set-titles on
# set -g set-titles-string '#S :: #(whoami) :: #h'


# window rename
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

set -g detach-on-destroy off  # don't exit from tmux when closing a session

set -g default-command zsh
# List of plugins
# # Supports `github_username/repo` or full git repo URLs
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-battery'

# Themes
# set -g @plugin 'fabioluciano/tmux-tokyo-night'
# set -g @theme_variation 'moon'
# set -g @theme_plugin_datetime_format '%D %H:%M'
# set -g @theme_plugins 'datetime,battery'
# set -g @theme_transparent_status_bar 'true'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"

run ~/.tmux/plugins/tmux/catppuccin.tmux
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum '
set -g @continuum-restore 'on'

set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_ORDER="window|session|pane|command|keybinding"
TMUX_FZF_LAUNCH_KEY="C-f"

run '~/.tmux/plugins/tpm/tpm'

