# Tmux settings
set -s escape-time 0
# Set XTerm key bindings
set-option -g xterm-keys on

# Set colors
set-option -g default-terminal "screen-256color"
set-option -sa terminal-features ',xterm-256color:RGB'

# Set reload key to r
bind r source-file ~/.tmux.conf

set -g prefix C-a
unbind C-b
bind C-a send-prefix

# go to last window
bind-key u last-window

# Count sessions start at 1
set -g base-index 1

# Use vim bindings
setw -g mode-keys vi
bind C-l send-keys 'C-l'

# Remap window navigation to vim
# unbind-key j
# bind-key j select-pane -D 
# unbind-key k
# bind-key k select-pane -U
# unbind-key h
# bind-key h select-pane -L
# unbind-key l
# bind-key l select-pane -R
#
# Set the title bar
set -g set-titles on
# set -g set-titles-string '#S :: #(whoami) :: #h'

# Set status bar
# set -g status-bg black
# set -g status-fg white
# set -g status-interval 5 
# set -g status-left-length 90
# set -g status-right-length 60
# set -g status-position top
# set -g status-left "#[fg=Green]#(whoami)#[fg=white]::#[fg=blue]#(hostname -s)#[fg=white]"
# set -g status-right '#[fg=Cyan]#S #[fg=white]%a %d %b %R'
# set -g status-justify left
# set-window-option -g window-status-current-format '#[bg=blue,fg=cyan,bold]#I#[bg=blue,fg=cyan]:#[fg=white]#W#[fg=dim]#F'
# set-window-option -g window-status-format '#[fg=cyan,dim]#I#[fg=blue]:#[default]#W#[fg=grey,dim]#F'

# window rename
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Sesh session manager
bind-key "o" run-shell "sesh connect \"$(
	sesh list -tz | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""
set -g detach-on-destroy off  # don't exit from tmux when closing a session

set -g default-command zsh
# List of plugins
# # Supports `github_username/repo` or full git repo URLs
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum '
set -g @plugin 'tmux-plugins/tmux-pain-control'
# set -g @plugin 'thesast/tmux-transient-status'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @theme_variation 'moon'
set -g @theme_plugin_datetime_format '%D %H:%M'
set -g @theme_plugins 'datetime,battery'
set -g @theme_transparent_status_bar 'true'
set -g @continuum-restore 'on'
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_ORDER="window|session|command|keybinding"
TMUX_FZF_LAUNCH_KEY="C-f"
#     # Other examples:
#     # github_username/plugin_name    \
#     # git@github.com/user/plugin     \
#     # git@bitbucket.com/user/plugin  \
#
#     # Initializes TMUX plugin manager.
#     # Keep this line at the very bottom of tmux.conf.

run-shell '~/.tmux/plugins/tpm/tpm'

