source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/bindkeys.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/history.zsh
source ~/.zsh/export.zsh
source ~/.zsh/basic.zsh
source $ZSH/oh-my-zsh.sh
